### ISSUE TITLE
Low balance popup always shows

### ISSUE THREAD

**Issue by ondrejfoltyn** [Lastaapps/menza#15]
Prý mi pořád dochází penízky i když mám přes 500 Kč. (Podle kódu se mi zdá, že by to mělo mít threshold na 256)

**Comment by Lastaapps** [comment]
To by nemělo dělat, kounu na to v blízké době, díky moc za report.

**Comment by Lastaapps** [comment]
Opraveno, ještě přidám nastavení tohodle limitu, fixnu další bugy a vydám to (takže to nebude venku hned dneska).
Ještě jednou díky za report.

commit 7a1bf846
