### ISSUE TITLE
Application closes (do not crash, no error reported) after chosing particular "menza" currently

### ISSUE THREAD

**Issue by Radian-Fi** [Lastaapps/menza#16]
Aplikace mi aktuálně padá při vybraní "Výdejna Karlovo náměstí". Při nastavení "Menza po spuštění:
Pamatovat si poslední" aplikace padá hned po spuštění (při vybraní "Výdejna Karlovo náměstí").

Android version:    34
App version name:   1.3.5
App version code:   1030500
Phone model:        Pixel 6
Phone manufacturer: Google 
Date and Time:      2024-02-19T09:16:11.302+01:00[Europe/Prague]
Screen size:        1080 x 2209 px

"Internal app problem"
2024-02-19T09:16:11.303
Unknown error message

**Comment by Lastaapps** [comment]
Zreprodukováno, kouknu na to večer, díky moc za report.

**Comment by Lastaapps** [comment]
Stejně jako poslední crash co jsem měl, tak chyba byla/je na straně menz ČVUT, zkusím ale udělat kód více odolný. Ještě jednou díky za report

Commit e7c22188
