### ISSUE TITLE
Error updating the account balance

### ISSUE THREAD

**Issue by Radian-Fi** [Lastaapps/menza#19]
Chyba někdy (jen někdy) nastává při aktualizaci balance (peněz) na účtu (jak automatické, tak manuální).

Android version:    34
App version name:   1.3.7
App version code:   1030700
Phone model:        Pixel 6
Phone manufacturer: Google 
Date and Time:      2024-02-29T11:11:25.926+01:00[Europe/Prague]
Screen size:        1080 x 2209 px

"Internal app problem"
2024-02-29T11:11:25.929
Could not find element "h4 span.badge"
it.skrape.selects.ElementNotFoundException: Could not find element "h4 span.badge"
	at tf.g.q(SourceFile:190)
	at ea.a.E(SourceFile:3)
	at ua.d.z(SourceFile:1521)
	at cg.a.k(SourceFile:9)
	at fj.n0.run(SourceFile:113)
	at lj.a.run(SourceFile:96)

**Comment by Lastaapps** [comment]
Dík za report. Teď to určitě neopravím, pokus se přihlásím přes agátu (což ČVUT login používá), tak dostanu tento error. Pro zajímavost, tobě to funguje? Jinak to nahlásím pánovi ICT SUZu a zkusim na to kouknout zítra, dneska nestíhám.

https://agata.suz.cvut.cz/jidelnicky/stravnik.php?lang=en

![image](https://github.com/Lastaapps/menza/assets/47794319/e05d14f1-5f77-4ff9-8ab1-dda3cf1b8005)

**Comment by Radian-Fi** [comment]
Já se přihlašuji přes ČVUT login. Teď mi například přihlášení na Agátě jde a jde mi i přihlášení v aplikaci, ale před pár minutami mi to ještě nešlo (mezitím jsem byl na obědě).

Takže to asi nefungovalo a zase to funguje (nicméně to není poprvé, co jsem podobný error dostal po otevření aplikace, když se snaží načíst stav peněz na účtu).

**Comment by Radian-Fi** [comment]
Teď je pro změnu spadla celá Agáta ( [agata.suz.cvut.cz](https://agata.suz.cvut.cz) se nenačítá [isitdownrightnow.com](https://www.isitdownrightnow.com/agata.suz.cvut.cz.html) píše, že je down). Takže nefunguje nic.

(A jak vidím, tak je dole víc webů pod doménou cvut.cz: [ist.cvut.cz](https://ist.cvut.cz/), [cips.cvut.cz](https://www.cips.cvut.cz/), [elsa.cvut.cz](https://elsa.cvut.cz/), [eshop.cvut.cz](https://eshop.cvut.cz/), [mentoring.cvut.cz](https://mentoring.cvut.cz/), atd.)

**Comment by Lastaapps** [comment]
Tak on byl down celej čvut, uvidím zítra. Ale upřímně nevim, co to může dělat.

Btw pokud to nejde, tak to nejde pro několik pokusů v kuse, nebo pro jeden ne a druhý třeba ano?

**Comment by Radian-Fi** [comment]
Nejsem si jistý, zda si to přesně pamatuji a nechtěl bych lhát. Ale mám pocit, že většinou se po manuálním pokusu (asi jednom, max. dvou pokusech) o aktualizaci už error neobjevil a aktualizace proběhla.
Nicméně v ten den, kdy později padlo skoro všechno pod cvut.cz doménou, mi vyskakoval error několikrát za sebou (a aktualizace neproběhla), pak kolem oběda to fungovalo a nakonec spadlo skoro všechno pod cvut.cz doménou (a to aplikace hlásila, že internet nedorazil).

Snad je to takhle správně, ale nevím, k čemu to bude, pokud se error nebude někdy replikovat... tzn. budu dávat pozor, a v případě, že bych na něj opět narazil, tak dám (sem) vědět i s podrobnostmi.

**Comment by Lastaapps** [comment]
Pokud se ti to podaří ještě jednou replikovat, tak to sem pošli a já zbuildim speciální variantu, co do toho error reportu přidá samotné html (to asi nechci na produkci). Sám jsem se taky přihlásil přes ČVUT a ne přes strávníka, tak to budu taky kontrolovat. Díky
