### ISSUE TITLE
Meal list margin

### ISSUE THREAD

**Issue by MichalLebeda** [Lastaapps/menza#2]
The meal list has an extra margin. 
I think that the list should be padded from the inside in a way that the first and last items have the same padding on top and bottom respectively. 

![image](https://user-images.githubusercontent.com/5246963/159462981-0b3de219-00fe-4d24-949a-93f6cee04119.png)

**Comment by Lastaapps** [comment]
You mean the difference between green and yellow margin?
![Screenshot_20220322-115058_Menza.png](https://user-images.githubusercontent.com/47794319/159466546-0ef3a5f3-5b88-4757-a17a-e10fd02018e3.png)

**Comment by vojta-horanek** [comment]
If this is a lazy list, this could be solved using the contentPadding parameter.

**Comment by MichalLebeda** [comment]
I mean that not a whole list widget should be padded, only first and last items INSIDE the widget

**Comment by Lastaapps** [comment]
Oh, I (probably) see. But as I know, API wasn't designed by Google to have padding there (so it's probably wrong design choice). It's easy to implement, don't get me wrong, but I don't see how this would make UI better, in other words I don't think there even should be additional padding in lists. But thanks for the report and feel free to argue.
