### ISSUE TITLE
Can't refresh without touch input

### ISSUE THREAD

**Issue by czM1K3** [Lastaapps/menza#20]
Zdravím, já jenom okomentuju moji recenzi na GP.
Když mám aplikaci na telefonu, tak input je samozřejmě jako dotyk a pull gesto funguje jak má. To samé se děje, když se k telefonu připojím z počítače pomocí [scrcpy](https://github.com/Genymobile/scrcpy), protože to simuluje dotyk. Problém, který já komentuju, pak nastává určitě pod [waydroidem](https://github.com/waydroid/waydroid/) na počítači, protože to používá nativní myš a myš logicky nepodporuje pull gesto. To samé chování očekávám i při připojení myši k telefonu, ale přímo jsem to nezkoušel.
Jakože upřímně je to takový edgecase, že se s tím asi nemá cenu zabývat. To proč jsem to zkoušel, tak to proto, že jsem na tu aplikaci zvyklý z telefonu a když se mi nechtělo vytahovat telefon, tak toto byla rychlejší volba.
Ostatní aplikace to upřímně moc neřeší, nebo spíš jsem na to moc nenarazil. Třeba takový aplikace [ViMusic](https://github.com/vfsfitvnm/ViMusic) se chová strašně divně při hoveru (je to hodně zbastlené).
Je to prostě primárně mobilní aplikace a na desktopu se prostě může chovat trochu divně no. Možná by šlo nějak získat, že je připojená myš a vyrenderovat tam refresh tlačítko, ale to asi nemá smysl.

**Comment by Lastaapps** [comment]
Nazdar, tohle jsem si hlavně chctěl zkusit, jak opravit. Udělal jsem to tak, jak bych an PC čekal - implementoval jsem Ctrl + R. Jedinej problém, kterej jsem asi za hodinu nevyřešil a to jsem docela ohýbal UI framework je, že se musí nejdříve zmáčkout Tab pro přesunutí focusu (aspoň u mě na emulované klávesnici). Až vyjde aktualizace (v pondělí snad bude venku), tak dej vědět, jak to jede/nejede. Díky

**Comment by czM1K3** [comment]
Teď jsem zkoušel tu verzi z Actiony a tak nějak mi Ctrl + R nic nedělá, ať dám focus kam chci. (Edit: na fyzickém telefonu s fyzickou klávesnicí to funguje, ale ve Waydroidu to nejde)

**Comment by czM1K3** [comment]
Tak teď jsem to zkoušel na notebooku, a když se teda dotabuju až do toho seznamu (začíná to v menu), tak tam to refreshne. Takže asi dobrý.
